default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: bookstore_backend_development

test:
  <<: *development
  database: bookstore_backend_test

production:
  url: <%= ENV['DATABASE_URL'] %>